version: "3"

services:
  # Main App
  mc-vanilla:
    image: itzg/minecraft-server
    container_name: mc
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      VERSION: LATEST   # バージョンをしてする場合 VERSION: 1.2.1
      TZ: 'Asia/Tokyo'
      MEMORY: 2G
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          memory: 2.5G  # enciroment.MEMORY * 1.25が推奨

          
  # Backup
  backup:
    image: itzg/mc-backup
    container_name: mc-backup
    depends_on:
    - mc-vanilla
    volumes:
      - ./data:/data:ro
      - ./mc-backups:/backups
    network_mode: "service:mc-vanilla"
    restart: always
